### ISSUE TITLE
Named arguments should identify the argument name

### ISSUE THREAD

**Issue by dmartinol** [modelcontextprotocol/registry#145]
**Is your feature request related to a problem? Please describe.**
Package arguments with named arguments should have a clear identification of the argument name and the possible default value.

Definitions like the following should not be allowed because we need to parse the name field to extract the argument name:
```json
        "package_arguments": [
          {
            "description": "Specify directory to work in.",
            "is_required": true,
            "format": "string",
            "value": "--directory path/to/cloned/repo/mcp-server-couchbase/",
            "default": "--directory path/to/cloned/repo/mcp-server-couchbase/",
            "type": "named",
            "name": "--directory path/to/cloned/repo/mcp-server-couchbase/",
            "value_hint": "path/to/cloned/repo/mcp-server-couchbase/"
          },
```

**Describe the solution you'd like**
The above should be converted to a simpler configuration with a clear definition of the argument name:
```json
        "package_arguments": [
          {
            "description": "Specify directory to work in.",
            "is_required": true,
            "format": "string",
            "value": "<VALUE>",
            "default": "<DEFAULT VALUE>",
            "type": "named",
            "name": "--directory",
            "value_hint": "path/to/cloned/repo/mcp-server-couchbase/"
          },
```

**Describe alternatives you've considered**

**Additional context**
After looking again at the seed file, I see that all the entries have package arguments where `value` is equal to `default`, so I cannot understand the difference between these fields, are we sure both of them are needed? The [schema](https://github.com/modelcontextprotocol/registry/blob/686fbe1e78117546c91dfb47051e405f0bd1762b/docs/openapi.yaml#L219C1-L232C1) is also not clear in specifying their purpose:
```yaml
        value:
          type: string
          description: |
            The default value for the input. If this is not set, the user may be prompted to provide a value.
...
        default:
          type: string
          description: The default value for the input.
```
